name: Alpaca Trading Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 14-21 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alpaca-trade-api requests

      - name: Debugging Output - Check Repository Contents
        run: |
          echo "Current directory: $(pwd)"
          echo "List files in current directory: $(ls)"
          echo "List files in Stocks directory: $(ls .github/workflows/Stocks)"

      - name: Run Alpaca Trading Script
        run: |
          # Navigate to the Stocks directory based on relative path
          cd .github/workflows/Stocks || exit 1

          # Search for the Stock.py file and store its path
          file_path=$(find . -type f -name "Stock.py" | head -n 1)

          # Check if the file was found
          if [ -f "$file_path" ]; then
            echo "File found at path: $file_path"
            python "$file_path"
          else
            echo "Error: Stock.py not found."
            exit 1
          fi
        env:
          ALPACA_API_KEY: ${{ secrets.PKBL3JHF9AQTJPEVXPB5 }}
          ALPACA_SECRET_KEY: ${{ secrets.lnYLaAvAp34Pr2BS6YRjf9sonIltjuVFuf2vIs3f }}
          WEATHER_API_KEY: ${{ secrets.bdb08a1cfe0e641014d62d0fca4d82a8 }}
