name: Alpaca Trading Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 14-21 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alpaca-trade-api requests


      - name: Run Alpaca Trading Script
        run: python Stock.py
        env:
          ALPACA_API_KEY: ${{ secrets.PKL9JQMNWF0FS4Z6X7I8 }}
          ALPACA_SECRET_KEY: ${{ secrets.qjJs7YcUZ9IcQa1siHzM8eZpFcTJ7vLbpaLOIr37 }}
          WEATHER_API_KEY: ${{ secrets.bdb08a1cfe0e641014d62d0fca4d82a8 }}
